name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Flutter
      - name: ðŸ¦ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      # Step 3: Create .env file and inject environment variables from GitHub secrets
      - name: ðŸ“ Create .env file
        run: |
          echo "PIXEL_BAY_API_KEY=${{ secrets.PIXEL_BAY_KEY }}" > .env
          echo "PIXEL_BAY_BASEURL=${{ secrets.PIXEL_BAY_BASEURL}}"> .env

      # Step 3: Build the Flutter web app
      - name: ðŸ”¨ Build Flutter Web
        run: flutter build web --release

      # Step 4: Deploy to GitHub Pages
      - name: ðŸš€ Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatically provided token
          publish_dir: build/web  # Deploy from the Flutter build directory
